spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db
    username: your_user
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    allow-bean-definition-overriding: true

redis:
  host: localhost
  port: 6379

logging:
  level:
    root: INFO

server:
  port: 8081
